language: python
python:
- '3.6'
cache: pip
install:
- make install
script:
- make test
notifications:
  slack:
    secure: f46jABKvxN82+MbbNFA2rp5dZrRpDJXaQr7tJAOZgVAlvfq5IRWmWgjluczFAZ4ibhChnSRVyfiFY9/ZlWWZ/9lvUgqN0kCollcWXVdp8ic7Ev3c9b+YNxzvYMSnI7GyI7ijT2jCF6fDQxJIKhI8+C0xSfwqboo7indxuYHJWyZje9XEsOLdsXo4uqHTPMU8VP1MNh47Sid+NIz6zlW59rgsYejIb9JlvlO8T2w/I24KyveSxaASRq1wUQEzVlfHW97U160SvS+sGhz7aoBoomWfRVH87P1/vcDLJ7CFSr1TqTERL+UwKG8zJawzNMTR06c9fnd7FZJ7bKumPufiCz982hXzllG3L+wjqzinbBr3/YxPpi9hBbQvS2OjJGjayYC9gYPBqV7Ts4WTmkSNkGcJkb/hxIwamOhREnNE36K9LPILUFUwCTltJuIaZ9H87daqa/tt9h4iKVICP1rUXD9MpwyP8GAc9Mw0DOg4gbtnKIoO5Jh1Eej9xkINJRnMTK2vPR/DVRFN3kemiKp775TucszZIZGWdHoM6kTPwNPTf4gqAfZlbaUh6xYFfizTtT6HZFGxqZ7NPXf+BbLKZqU8fWJ2smHQ2M5TUHiVcbb/BAWhUnNO3wa6Xx8sMaH1H1joLcrUCdVz8GYZSPTyT4lAtaaw782odnlsr5BpAUs=
