language: python
python:
- '3.6'
cache: pip
install:
- make install
script:
- make test
notifications:
  slack:
    secure: F08mFodWt9hosLBXRSdoz5TRZr1/m7p7K4IMwFO2hWanIZfApmgVV9gOh8ZIXlJDCIdUJ4fAKAP+I7q7uw7sfwosPxhQL7UDQJrFCTJVOgpPPq2e2vHxkkZOfmwIf1xDIqEoJxEq5Qa7vdCYqp8z1LDPaDRDn8awjj4FlNuXDb2SGYvJS3JonK76pBm+7LP9jDsVrLAQQIW+xyDhZVBE6o9YDUox1RD3judysd39j6slG+eJNc3fTCliMT5yY0f6oMTrf5CkJ2PRB6b4B7/6YH7ZO4Nx8hU1RY+JLEdZLS6yGhzjW6Eg3LBSvibdGOF3O45mXry0a2PG6+JQsA8aksXsVPO96VOgAvYTKSXbx5qOrUNtRn6vfBrQw4mDcbu1nvmJUHuj9FcrrDM8+PDJWG1stm/RonpjKHFV/3P5EunD/741WeLoG/QODamlce7/H9Lf53XBh79KsCYG5Uc/KMgS0U5biPHdgoDYlQlrsMsA5bnRnUbNBAyaxMoK5OfFsRDZ05ruP58BQ/60GfG3mUS+b420/T8+/SVxvW2u63KyDzDIhxXTFd/fm9AbUFxXbrFBcM90npD2LQMXYOL2YWvpnzxILOgysgEbPIhNh+Zmec/tiFChP3KImjUZTdGFDs7FHYv9sKY9qWjJXO7pGXjUeJKzYaiA2XlQkmDaTDM=
